### ISSUE TITLE
履歴 保持の実装例

### ISSUE THREAD

**Issue by koichi-tsujino-aispirits** [shohei1029/book-azureopenai-sample#12]
5. 3. 1 履歴保持の実装 例

次に、 183 行 目 に 先ほど コピー し た Cosmos DB の 接続 情報 を セット し ます。 < Your-CosmosDB-AccountID > を「 アカウント ID」 に、 < Your-CosmosDB-Access-Key > を「 アクセス キー」 に 置き換え ます（ リスト 5. 5）。
だけでは、アプリケーションエラーが出ます。key の設定以下の部分のコメントを外す必要がありました。

# Set up a Cosmos DB client to store the chat history
    endpoint = < Your-CosmosDB-AccountID >
    key = < Your-CosmosDB-Access-Key >
    cosmos_container = []
    try:
        cosmos_client = CosmosClient(url=endpoint, credential=key)
        database = cosmos_client.create_database_if_not_exists(id="ChatGPT")
        partitionKeyPath = PartitionKey(path="/id")
        cosmos_container = database.create_container_if_not_exists(
            id="ChatLogs", partition_key=partitionKeyPath
        )
    except Exception as e:
        logging.exception(e)
        pass

**Comment by nohanaga** [comment]
ご指摘ありがとうございました。内容確認の上、修正させていただきます。

**Comment by koichi-tsujino-aispirits** [comment]
よろしくお願いします。
