### ISSUE TITLE
azd up 実行時tiktokenのinstall時にRustのコンパイラーがないとエラーになる

### ISSUE THREAD

**Issue by crebo-t-yokoyama** [shohei1029/book-azureopenai-sample#15]
windows11で実行しています。
`azd up`
実行後、azureの各種リソースは作成していることは確認できました。
![image](https://github.com/shohei1029/book-azureopenai-sample/assets/169870228/185d9c47-7d2e-48e5-85b7-83c23df861d1)

また、最終的にはエンドポイントも出力され、SUCCESSと表示されます。
![image](https://github.com/shohei1029/book-azureopenai-sample/assets/169870228/72ebbf45-0e84-422f-8be7-41e097269743)

ただエンドポイントにアクセスしプロンプトを投げるとエラーが返却されます。

`azd up`の途中で画像のようなエラーが発生しています。
![image](https://github.com/shohei1029/book-azureopenai-sample/assets/169870228/1f439f9d-011e-4b93-b338-e985c51be6b0)
これが原因かと思っているのですが、対処法が不明のためご教授いただければ幸いです。

**Comment by nohanaga** [comment]
ご連絡遅くなり申し訳ありません。
この問題は使用している ticktoken のバージョンが Python 3.12 に対応していないため発生しているようです。
https://github.com/openai/tiktoken/issues/205

今後この問題が出ないように prepdocs.py を最新化しようと考えていますが、お手数ですが現状は [Python 3.10](https://github.com/shohei1029/book-azureopenai-sample?tab=readme-ov-file#1-python-31011-%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB) 系をインストールしてトライしていだけますでしょうか。

**Comment by nohanaga** [comment]
`prepdocs.py` および `requirements.txt` を最新版に Update しましたので動くかと思います。

**Comment by crebo-t-yokoyama** [comment]
ご対応ありがとうございます。
後日再度実行してみます。

**Comment by crebo-t-yokoyama** [comment]
@nohanaga 
ご対応ありがとうございました。
再度試したところ、azd up 完了し、webアプリも正常に動作しました。

**Comment by nohanaga** [comment]
解決したので Close いたします。
