### ISSUE TITLE
191ページのもう一度聞くについて

### ISSUE THREAD

**Issue by 1mlzesb** [shohei1029/book-azureopenai-sample#16]
図8.2［もう一度聞く］ボタンのイメージの内容はコードの中では探せないですが、
もし実行して見られる環境の情報を教えて頂けますか
また、193ページの図8.3にある参照元の実装も情報があれば教えて頂けますか

**Comment by nohanaga** [comment]
返信遅くなり申し訳ありません。

図8.2［もう一度聞く］はリスト 8.1 を [aoai-flask-sse](https://github.com/shohei1029/book-azureopenai-sample/tree/cfc37801d3872e35cbe43ef84be55e0b6bf5162b/aoai-flask-sse) に実装することで実現できるかと思います
@yoshidashingo  さんこの認識で正しいです？

図8.3 にあるような出典の表示につきましては、P120 図5.11 でも解説しておりまして、こちらは [aoai-rag](https://github.com/shohei1029/book-azureopenai-sample/tree/main/aoai-rag) のほうのサンプルに実装されております。
