### ISSUE TITLE
デプロイして、URLをクリックしてアプリを実行したらエラーが発生しました

### ISSUE THREAD

**Issue by kentarQue** [shohei1029/book-azureopenai-sample#18]
Error: () The index 'gptkbindex' for service '*********' was not found.
Code:
Message: The index 'gptkbindex' for service '*********' was not found.
以上のようなエラーが出るのですがどう対処したらいいのかわかりませんでしたので、ご教示のほどよろしくお願いいたします。
********はリソース名を伏せている形にしております

p113の内容です

**Comment by nohanaga** [comment]
`azd up` 実行の際に何らかのエラーが出ていませんでしたでしょうか。
コマンドを再度実行して内容をご確認いただけると助かります。
