### ISSUE TITLE
azd up にてエラー

### ISSUE THREAD

**Issue by bizyas** [shohei1029/book-azureopenai-sample#19]
以下のエラーが出力されました。
何か対処方法があれば教えて頂けると幸いです。

/bin/sh: ./scripts/prepdocs.sh: Permission denied

ERROR: error executing step command 'provision': failed running post hooks: 'postprovision' hook failed with exit code: '126', Path: './scripts/prepdocs.sh'. : exit code: 126

**Comment by nohanaga** [comment]
`azd up` の前に `./scripts/prepdocs.sh` に実行権限を付与してから再実行をお願いいたします。
例: `chmod 755 ./scripts/prepdocs.sh`

**Comment by bizyas** [comment]
上記エラー解決することができました。ありがとうございました。
