### ISSUE TITLE
既存のリソースでのデプロイで失敗する

### ISSUE THREAD

**Issue by hawks-6026** [shohei1029/book-azureopenai-sample#6]
## 概要
[既存のリソースでのデプロイ](https://github.com/shohei1029/book-azureopenai-sample/tree/main/aoai-rag#%E6%97%A2%E5%AD%98%E3%81%AE%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9%E3%81%A7%E3%81%AE%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4)で失敗します。

## エラーメッセージ
```
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
BadRequest: NetworkAcls is required for this resouce.

```
## 環境変数
環境変数は以下となっています。
AI Search、Azure OpenAIは既存を指定し、それ以外は新規。
```
> azd env get-values

AZURE_ENV_NAME="環境名"
AZURE_LOCATION="japaneast"
AZURE_OPENAI_CHATGPT_DEPLOYMENT="既存デプロイ名"
AZURE_OPENAI_EMB_DEPLOYMENT="既存デプロイ名"
AZURE_OPENAI_RESOURCE_GROUP="既存リソースグループ名"
AZURE_OPENAI_SERVICE="既存OpenAI名"
AZURE_SEARCH_SERVICE="既存AI Search名"
AZURE_SEARCH_SERVICE_RESOURCE_GROUP="既存リソースグループ名"
AZURE_SUBSCRIPTION_ID="XXXXX"

> azd up

```
AI Search、Azure OpenAIともにネットワーク設定は`すべてのネットワーク`としています。
対応方法についてご教授いただきたいです。

**Comment by da-yamaguchi** [comment]
以下の情報を元に`aoai-rag\infra\core\ai\cognitiveservices.bicep`を修正し、実行したところ解消しました。

https://github.com/Azure-Samples/azure-search-openai-demo/issues/122
https://github.com/Azure-Samples/azure-search-openai-demo/issues/133
https://github.com/Azure/azure-dev/pull/3033

**Comment by hawks-6026** [comment]
以下の情報を元に`aoai-rag\infra\core\ai\cognitiveservices.bicep`を修正し、実行したところ解消しました。

https://github.com/Azure-Samples/azure-search-openai-demo/issues/122
https://github.com/Azure-Samples/azure-search-openai-demo/issues/133
https://github.com/Azure/azure-dev/pull/3033

**Comment by nohanaga** [comment]
ご指摘いただきありがとうございます。
`aoai-rag/infra/core/ai/cognitiveservices.bicep` に、networkAcls の[設定](https://github.com/shohei1029/book-azureopenai-sample/commit/de800cd622f2b2701e9ee3f997bacdd4d29f90e7)を入れました。
