### ISSUE TITLE
第5章　5.2.6 追加のドキュメントをインデックス化する

### ISSUE THREAD

**Issue by Arkwkun** [shohei1029/book-azureopenai-sample#7]
Widdows環境のPowerShellで
 prepdocs.ps1を実行したところ下記メッセージが出力されました。
 
 これは実行に必要なファイルが適切なディレクトに無いという意味でしょうか？
 その場合どのファイルをどのディレクトリに置いて実行するのがただしいでしょうか？
 
 PS C:\Users\xxxxx\book-azureopenai-sample\aoai-rag\scripts> .\prepdocs.ps1

Loading azd .env file from current environment

Environment variables set.
Creating python virtual environment "scripts/.venv"
Installing dependencies from "requirements.txt" into virtual environment
ERROR: Could not open requirements file: [Errno 2] No such file or directory: './scripts/requirements.txt'

Running "prepdocs.py"
C:\Users\h051873\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\h051873\\book-azureopenai-sample\\aoai-rag\\scripts\\scripts\\prepdocs.py': [Errno 2] No such file or directory
PS C:\Users\h051873\book-azureopenai-sample\aoai-rag\scripts> C:\Users\h051873\book-azureopenai-sample\aoai-rag\scripts\scripts\.venv\scripts\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\h051873\book-azureopenai-sample\aoai-rag\scripts\scripts\.venv\lib\site-packages (23.0.1)
Collecting pip

**Comment by nohanaga** [comment]
直接 prepdocs.ps1 を実行する際は、一旦一つ上のディレクトリ（`C:\Users\xxxxx\book-azureopenai-sample\aoai-rag`）に移動してから以下のようにして実行してみてください。

```ps
PS cd ../
PS ./scripts/prepdocs.ps1
```

**Comment by Arkwkun** [comment]
ありがとうございます。助かりました。
