### ISSUE TITLE
azd upでThis command cannot be run due to the error: 指定されたファイルが見つかりません。　が発生する

### ISSUE THREAD

**Issue by acs-katoryota** [shohei1029/book-azureopenai-sample#8]
第５章の自動構築スクリプトの起動(azd up)において以下のエラーが出力されました。
このまま継続して手順を進めてよいものか判断がつかないためご教示お願いいたします。

![image](https://github.com/shohei1029/book-azureopenai-sample/assets/70707674/4c83ce38-43e8-4695-856a-feddf46b64ff)

**Comment by nohanaga** [comment]
`azd up` を実行するときの Powershell のカレントディレクトリを `C:\xxxxx\book-azureopenai-sample\aoai-rag` にしていただきたいのですが、すでに `aoai-rag` で実行されていますでしょうか。

**Comment by nohanaga** [comment]
コチラ詳しく解析いただき大変感謝しております。
